spring.application.name=borrowbox

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/borrowbox_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Nyayt@3m0}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=${JWT_SECRET:borrowbox_super_secret_key_1234567890_abcdef}
app.jwt.issuer=${JWT_ISSUER:borrowbox}
app.jwt.exp-minutes=${JWT_EXP_MINUTES:60}
app.admin.email=${APP_ADMIN_EMAIL:}

server.port=8080

logging.level.org.springframework.security=DEBUG
